version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: grammergamedb
      POSTGRES_USER: grammergamedbadmin
      POSTGRES_PASSWORD: grammergamedbpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

#command: [ "-c", "listen_addresses='*'" ]

